# Summary

Summary
This study will explore the relationship between gastrointestinal activity and emotions utilizing electrogastrography. The specific aims of this study are to (1) establish a relationship between emotionally arousing stimuli and the EGG response, (2) investigate the individual differences that might influence the EGG response to stress (such as early life stress, current stress, trait variables, etc.), (3) examine how the EGG response sits with other physiological indices (such as heart rate and sweat response), and (4) explore the ways in which physical sensations are associated with emotions and physiological responses.

We will recruit N = 200 (minimum 150) adult participants. Participants will watch a series of sad, scary, and neutral movies while electrophysiology recordings are made. Then they will complete a range of questionnaires assessing social and emotional functioning, physical health symptoms, early life adversity, and physical health assessments.

Keywords
egg, stress, emotions, physiology

Background
While we often describe our emotions as "gut feelings", surprisingly little research has examined how emotions and the gastrointestinal system interact. Physiological methods such as heart rate and sweat response are common indicators of emotional arousal, but the electrograstrogram (EGG) is seldom used in psychological research. Given that gastrointestinal and mental heath problems are highly comorbid, with anxiety five times higher in individuals with irritable bowel syndrome (IBS) than in those with no IBS symptoms (Lee et al., 2009), gastrointestinal activity may serve as a useful indicator of emotional functioning. In one study, researchers found that movie clips capturing emotions of fear, disgust, and sadness, elicited a greater EGG response relative to a neutral condition (Vianna & Tranel, 2006).

Interestingly, few studies have explored the way that individual differences, such as anxiety, depression, stress, and early adversity might influence the EGG response to these negatively emotionally arousing movie clips. For example, stress in early life can affect both emotional and gastrointestinal symptoms and functioning. One study demonstrated that previous adverse care experiences were associated with both increased anxiety and incidence of gastrointestinal symptoms in youth (Callaghan et al., 2019). In addition, early adversity was associated with changes in gastrointestinal microbiome diversity that were correlated with neural activation to emotional faces (Callaghan et al., 2019).

Using electrogastrography, we seek to investigate the relationship between gastric myoelectrical activity and emotionally arousing movie clips. We also hope to explore factors that might influence gastrointestinal responses to emotional arousal, and whether and how physical sensations are associated with emotions and physiological responses. We also hope to evaluate how EGG sits with other physiological measures, such as heart rate and sweat response, in order to explore whether emotional patterning of physiological responses contribute to meaningful differences in emotion regulation, the stress response, and mental health.

Specific Aims
The study will test several hypotheses.

1 - Establish a relationship between emotionally arousing stimuli and the EGG response.

There will be a greater EGG response (i.e. average peak amplitude) for the sad and scary movie condition relative to the neutral movie condition.
The intensity of subjective emotion will be positively correlated with EGG response.
2 - Investigate the individual differences that might influence the EGG response to stress (such as early life stress, current stress, trait variables, etc.)

Increased levels of emotional distress, such as anxiety and depression, will be associated with greater EGG response during the emotionally arousing movie conditions.
Early life stress will be associated with greater EGG response in the emotionally arousing movie conditions, relative to individuals who did not experience early life stress.
Greater current and perceived stress will be associated with greater EGG response in the emotionally arousing conditions.
3 - Examine how the EGG response sits with other physiological indices (such as heart rate and sweat response)

The EGG response will be associated with other physiological indices of emotional arousal, such as heart rate and sweat response.
4 - Explore the ways in which physical sensations are associated with emotions and physiological responses

Lower interoceptive awareness will be associated with greater physiological responses to emotionally arousing stimuli.
Higher somatic symptomology will be associated with greater physiological responses to emotionally arousing stimuli.
Distinct dimensions of physical sensations and physiological responding will be positively correlated.
Gastrointestinal symptoms will be associated with both greater anxiety and greater EGG response to emotionally arousing stimuli.