# COVID-19 Sub-Study

## Summary

This substudy will explore the relationship between the global COVID-19 pandemic, somatic symptoms, and psychological stress. 

This study will explore the relationship between emotions and somatic symptamology in the wake of the COVID-19 pandemic, while exploring individual differences in social, environmental, personality, and lifestyle factors which may mitigate or exacerbate the negative psychological impact of this stressor. 

The specific aims of this study are to (1) establish a relationship between psychological stress and somatic symptoms as assessed by our newly developed Somatic Symptoms of Negative Affect (somna) questionnaire, (2) investigate the individual differences that might influence the somatic and psychological response to stress (such as early life stress, social support, media consumption, diet and exercise, lifestyle habits, trait variables, etc.), and (3) examine how specific somatic symptoms in the context of stress may relate to mental health.

We will recruit N = 200 (minimum 150) adult participants. Participants will be recruited online from the UCLA participant pool in the university term directly after the outbreak of COVID-19. Participants will complete a range of questionnaires assessing current levels of stress, social and emotional support and functioning, physical health symptoms, early life adversity, media exposure and consumption, and lifestyle factors.

## Keywords
stress, emotions, mental health, somatic symptoms

## Background


## Specific Aims
The study will test several hypotheses.

1. Establish a relationship between emotionally arousing stimuli and the EGG response.
    - There will be a greater EGG response (i.e. average peak amplitude) for the sad and scary movie condition relative to the neutral movie condition.
    - The intensity of subjective emotion will be positively correlated with EGG response.

2. Investigate the individual differences that might influence the EGG response to stress (such as early life stress, current stress, trait variables, etc.)
    - Increased levels of emotional distress, such as anxiety and depression, will be associated with greater EGG response during the emotionally arousing movie conditions.
    - Early life stress will be associated with greater EGG response in the emotionally arousing movie conditions, relative to individuals who did not experience early life stress.
    - Greater current and perceived stress will be associated with greater EGG response in the emotionally arousing conditions.

3. Examine how the EGG response sits with other physiological indices (such as heart rate and sweat response)
    - The EGG response will be associated with other physiological indices of emotional arousal, such as heart rate and sweat response.

4. Explore the ways in which physical sensations are associated with emotions and physiological responses
    - Lower interoceptive awareness will be associated with greater physiological responses to emotionally arousing stimuli.
    - Higher somatic symptomology will be associated with greater physiological responses to emotionally arousing stimuli.
    - Distinct dimensions of physical sensations and physiological responding will be positively correlated.
    - Gastrointestinal symptoms will be associated with both greater anxiety and greater EGG response to emotionally arousing stimuli.