# References

Allan, S. & Gilbert, P. (1995). A social comparison scale: Psychometric properties and
relationship to psychopathology. Personality and Individual Differences, 19, 293-299.

Beck, A. T., Steer, R. A., & Brown, G. K. (1996). Beck depression inventory-II. San Antonio, 78(2), 490-498.

Bernstein DP, Fink L, Handelsman L, Lovejoy M, Wenzel K, Sapareto E, Gurriero J. (1994). Initial reliability and
validity of a new retrospective measure of child abuse and neglect. Am J Psychiatry; 151: 1132-
1136

Booth, M.L. (2000). Assessment of Physical Activity: An International Perspective. Research Quarterly for Exercise and Sport, 71 (2): s114-20.

Buysse, D.J., Reynolds III, C.F., Monk, T.H., Berman, S.R., & Kupfer, D.J. (1989). The Pittsburgh Sleep Quality Index: A new instrument for psychiatric practice and research. Journal of Psychiatric Research, 28(2), 193-213.

Callaghan, B. L., Fields, A., Gee, D. G., Gabard-Durnam, L., Caldera, C., Humphreys, K. L., Goff, B., Flannery, J., Telzer, E. H., Shapiro, M., & Tottenham, N. (2020). Mind and gut: Associations between mood and gastrointestinal distress in children exposed to adversity. Development and Psychopathology, 32(1), 309–328. https://doi.org/10.1017/S0954579419000087

Carleton, R. N., Norton, M. A. P. J., & Asmundson, G. J. G. (2007). Fearing the unknown: A short version of the Intolerance of Uncertainty Scale. Journal of Anxiety Disorders, 21(1), 105–117. https://doi.org/10.1016/j.janxdis.2006.03.014

Cardeña, E., Koopman, C., Classen, C., Waelde, L. C., & Spiegel, D. (2000). Psychometric properties of the Stanford Acute Stress Reaction Questionnaire (SASRQ): A valid and reliable measure of acute stress. Journal of Traumatic Stress, 13(4), 719–734. https://doi.org/10.1023/A:1007822603186

Cohen, S., Kamarck, T., and Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24, 386-396. 

Crandall, C.S., Preisler, J.J., & Aussprung, J. (1992). Measuring life event stress in the lives of college students: The undergraduate stress questionnaire. Journal of Behavioral Medicine, 15, 627-662.

Firestein, M., & Callaghan, B. (2019). The brain–gut connection: Environmental influences on gastrointestinal biology and neurobehavior across development. Developmental Psychobiology, 61(5), 639–639. https://doi.org/10.1002/dev.21869

Gabrys, R. L., Tabri, N., Anisman, H., & Matheson, K. (2018). Cognitive Control and Flexibility in the Context of Stress and Depressive Symptoms: The Cognitive Control and Flexibility Questionnaire. Frontiers in Psychology, 9. https://doi.org/10.3389/fpsyg.2018.02219

John, O. P., & Srivastava, S. (1999). The Big-Five trait taxonomy: History, measurement, and theoretical perspectives. In L. A. Pervin & O. P. John (Eds.), Handbook of personality: Theory and research (Vol. 2, pp. 102–138). New York: Guilford Press. 

Körber, S., Frieser, D., Steinbrecher, N., & Hiller, W. (2011). Classification characteristics of the Patient Health Questionnaire-15 for screening somatoform disorders in a primary care setting. Journal of Psychosomatic Research, 71(3), 142–147. https://doi.org/10.1016/j.jpsychores.2011.01.006

Lee, S., Wu, J., Ma, Y. L., Tsang, A., Guo, W.-J., & Sung, J. (2009). Irritable bowel syndrome is strongly associated with generalized anxiety disorder: A community study. Alimentary Pharmacology & Therapeutics, 30(6), 643–651. https://doi.org/10.1111/j.1365-2036.2009.04074.

Lyubomirsky, S., & Lepper, H. (1999). A measure of subjective happiness: Preliminary reliability and construct validation. Social Indicators Research, 46, 137-155.

Mehling, W. E., Price, C., Daubenmier, J. J., Acree, M., Bartmess, E., and Stewart, A. (2012). The multidimensional assessment of interoceptive awareness (MAIA). PLoS ONE 7:e48230. doi: 10.1371/journal.pone.0048230

Pennebaker, J. W. (1982). The Psychology of Physical Symptoms. New York: Springer-Verlag.

Pennebaker, J. W. (1997). Writing About Emotional Experiences as a Therapeutic Process. Psychological Science, 8(3), 162–166. https://doi.org/10.1111/j.1467-9280.1997.tb00403.x

Pennebaker, J.W. & Susman, J.R. (2013) Childhood Trauma Questionnaire. Measurement Instrument Database for the Social Science. Retrieved from www.midss.ie

Russell, D , Peplau, L. A.. & Ferguson, M. L. (1978). Developing a measure of loneliness. 
Journal  of Personality Assessment, 42, 290-294.

Salkovskis, M, Rimes, K.A., Warwick, H.M.C, Clark, D.M. The Health Anxiety Inventory: development and validation of scales for the measurement of health anxiety and hypochondriasis. Psychol Med. 2006; 32(5):843–853.

Savci, M., & Griffiths, M. D. (2019). The Development of the Turkish Social Media Craving Scale (SMCS): A Validation Study. International Journal of Mental Health and Addiction. https://doi.org/10.1007/s11469-019-00062-9

Sinclair, V. G., & Wallston, K.A. (2004). The development and psychometric evaluation of the Brief Resilient Coping Scale. Assessment, 11 (1), 94-101.  

Spielberger, C. D., Gorsuch, R. L., Lushene, R., Vagg, P. R., & Jacobs, G. A. (1983). Manual for the State-Trait Anxiety Inventory. Palo Alto, CA: Consulting Psychologists Press.

Steiner, M., Macdougall, M., & Brown, E. (2003). The premenstrual symptoms screening tool (PSST) for clinicians. Archives of Women’s Mental Health, 6(3), 203–209. https://doi.org/10.1007/s00737-003-0018-4

Tedeschi, R. G., & Calhoun, L. G. (1996). The Posttraumatic Growth Inventory: Measuring the positive legacy of trauma. Journal of Traumatic Stress, 9(3), 455–471. https://doi.org/10.1007/bf02103658

Varni, J.W., Kay, M.T., Limbers, C.A., Franciosi, J.P., & Pohl, J.F. (2012). PedsQL™ Gastrointestinal Symptoms Module item development: Qualitative methods. Journal of Pediatric Gastroenterology & Nutrition, 54, 664-671

Vianna, E. P. M., & Tranel, D. (2006). Gastric myoelectrical activity as an index of emotional arousal. International Journal of Psychophysiology, 61(1), 70–76. https://doi.org/10.1016/j.ijpsycho.2005.10.019

Zimet, G.D., Dahlem, N.W., Zimet, S.G. & Farley, G.K. (1988). The Multidimensional Scale of 
Perceived Social Support. Journal of Personality Assessment, 52, 30-41. 



